from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from . import read, run


"""
Section 1: Required inputs, plotting defaults, and returned containers.
This section defines which saved outputs the analysis stage depends on, which
columns must be present in those files, and the compact summary returned to
`main.py` after the interactive figures have been displayed.
"""

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs"

ZOOM_WINDOW_SECONDS = 0.25
PLOT_RENDERER = "browser"
PLOT_TEMPLATE = "plotly_white"

PREPARED_REQUIRED_COLUMNS = {
    "source_file",
    "case_name",
    "case_group",
    "dataset_role",
    "is_confirmation",
    "flow_time",
    "cl",
    "cd",
    "pitch",
}

PREDICTION_REQUIRED_COLUMNS = {
    "case_name",
    "case_group",
    "dataset_role",
    "is_confirmation",
    "flow_time",
    "cl",
    "cd",
    "pitch",
    "cl_pred",
    "cd_pred",
    "cl_residual",
    "cd_residual",
}

RUN_SUMMARY_REQUIRED_COLUMNS = {
    "case_name",
    "rmse_cl",
    "rmse_cd",
    "mae_cl",
    "mae_cd",
}


"""
Container: AnalysisStageOutput.
This container records the basic facts about the analysis run so `main.py` can
report how many figures were displayed and how many cases were inspected.
"""


@dataclass(frozen=True)
class AnalysisStageOutput:
    displayed_figure_count: int
    prepared_case_count: int
    confirmation_case_count: int


"""
Section 2: Input loading and schema validation.
These helpers load the prepared and prediction outputs written by earlier
stages and stop immediately if any required file or required column is missing.
"""


"""
Function: _load_required_csv.
Loads one required analysis input file and raises a clear error if the file has
not been generated by an earlier workflow stage yet.
"""


def _load_required_csv(path: Path, description: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"{description} not found at {path}. "
            "Run the required earlier stage before the analysis stage."
        )
    return pd.read_csv(path)


"""
Function: _require_columns.
Checks whether a loaded analysis input file contains the minimum columns needed
for the plots defined in this first analysis increment.
"""


def _require_columns(
    table: pd.DataFrame,
    required_columns: set[str],
    description: str,
) -> None:
    missing_columns = required_columns - set(table.columns)
    if missing_columns:
        raise ValueError(
            f"{description} is missing required columns: {sorted(missing_columns)}"
        )


"""
Function: _load_analysis_inputs.
Loads and validates all CSV inputs used by the analysis stage so later plotting
helpers can assume the data is complete and ready to use.
"""


def _load_analysis_inputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    prepared_train_table = _load_required_csv(
        read.OUTPUT_DIR / read.OUTPUT_FILENAMES["train"],
        "Prepared training cases",
    )
    prepared_confirmation_table = _load_required_csv(
        read.OUTPUT_DIR / read.OUTPUT_FILENAMES["confirmation"],
        "Prepared confirmation cases",
    )
    prediction_table = _load_required_csv(
        run.OUTPUT_DIR / run.LATEST_PREDICTIONS_FILENAME,
        "Latest confirmation predictions",
    )
    run_summary_table = _load_required_csv(
        run.OUTPUT_DIR / run.LATEST_SUMMARY_FILENAME,
        "Latest confirmation run summary",
    )

    _require_columns(
        prepared_train_table,
        PREPARED_REQUIRED_COLUMNS,
        "Prepared training cases",
    )
    _require_columns(
        prepared_confirmation_table,
        PREPARED_REQUIRED_COLUMNS,
        "Prepared confirmation cases",
    )
    _require_columns(
        prediction_table,
        PREDICTION_REQUIRED_COLUMNS,
        "Latest confirmation predictions",
    )
    _require_columns(
        run_summary_table,
        RUN_SUMMARY_REQUIRED_COLUMNS,
        "Latest confirmation run summary",
    )

    prepared_table = pd.concat(
        [prepared_train_table, prepared_confirmation_table],
        ignore_index=True,
    )
    if prepared_table.empty:
        raise ValueError("No prepared cases are available for analysis.")
    if prediction_table.empty:
        raise ValueError("No confirmation predictions are available for analysis.")

    return prepared_table, prediction_table, run_summary_table


"""
Section 3: Shared table-preparation helpers.
These helpers derive small analysis-only fields that make the overview and
comparison figures easier to build and easier to interpret.
"""


"""
Function: _prepare_case_time_axes.
Adds a retained-time-from-start column per case. The full-range plots continue
to use absolute `flow_time`, while the zoomed plots use the retained local time
so every case can be compared over its first 0.25 seconds.
"""


def _prepare_case_time_axes(table: pd.DataFrame) -> pd.DataFrame:
    ordered_table = table.sort_values(by=["case_name", "flow_time"]).copy()
    ordered_table["time_from_case_start"] = (
        ordered_table["flow_time"]
        - ordered_table.groupby("case_name")["flow_time"].transform("min")
    )
    return ordered_table


"""
Function: _zoomed_table.
Filters a case-based table to the first retained analysis window measured from
the retained start of each case.
"""


def _zoomed_table(table: pd.DataFrame) -> pd.DataFrame:
    return table.loc[
        table["time_from_case_start"] <= ZOOM_WINDOW_SECONDS
    ].copy()


"""
Function: _trace_style.
Returns a small style dictionary that keeps confirmation cases visually
distinct from training cases throughout the overview plots.
"""


def _as_bool_flag(value: object) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() == "true"
    return bool(value)


def _trace_style(is_confirmation: bool) -> dict[str, object]:
    return {"dash": "dash"} if is_confirmation else {"dash": "solid"}


"""
Function: _show_figure.
Displays one Plotly figure and prints lightweight progress information so the
analysis stage stays readable even when many figures are opened in sequence.
"""


def _show_figure(
    figure: go.Figure,
    figure_index: int,
    total_figures: int,
) -> None:
    print(
        f"[analyse] displaying figure {figure_index}/{total_figures}: "
        f"{figure.layout.title.text}",
        flush=True,
    )
    figure.show(renderer=PLOT_RENDERER)


"""
Section 4: Dataset-overview figure builders.
These helpers create the cross-case inspection plots requested for `cl`, `cd`,
and `pitch`, both across all cases and grouped by starting-letter category.
"""


"""
Function: _overview_trace.
Builds one overview trace for a single case and one selected signal.
"""


def _overview_trace(
    case_table: pd.DataFrame,
    signal_name: str,
    x_column: str,
) -> go.Scatter:
    case_name = str(case_table["case_name"].iloc[0])
    dataset_role = str(case_table["dataset_role"].iloc[0]).title()
    is_confirmation = _as_bool_flag(case_table["is_confirmation"].iloc[0])

    return go.Scatter(
        x=case_table[x_column],
        y=case_table[signal_name],
        mode="lines",
        name=case_name,
        legendgroup=case_name,
        hovertemplate=(
            f"Case: {case_name}<br>"
            f"Role: {dataset_role}<br>"
            f"Time: %{{x:.6f}}<br>"
            f"{signal_name}: %{{y:.6f}}<extra></extra>"
        ),
        line=_trace_style(is_confirmation),
    )


"""
Function: _build_all_case_signal_figure.
Creates one full-range or zoomed overlay figure for one selected signal across
all prepared cases.
"""


def _build_all_case_signal_figure(
    prepared_table: pd.DataFrame,
    signal_name: str,
    x_column: str,
    title: str,
    x_axis_title: str,
) -> go.Figure:
    figure = go.Figure()

    for _, case_table in prepared_table.groupby("case_name", sort=True):
        ordered_case_table = case_table.sort_values(by=x_column).reset_index(drop=True)
        figure.add_trace(
            _overview_trace(
                case_table=ordered_case_table,
                signal_name=signal_name,
                x_column=x_column,
            )
        )

    figure.update_layout(
        title=title,
        template=PLOT_TEMPLATE,
        width=1200,
        height=700,
        legend_title="Case",
    )
    figure.update_xaxes(title_text=x_axis_title)
    figure.update_yaxes(title_text=signal_name)
    return figure


"""
Function: _build_grouped_signal_figure.
Creates one selected-signal figure with a separate subplot row for each
starting-letter case group so related simulations can be inspected together.
"""


def _build_grouped_signal_figure(
    prepared_table: pd.DataFrame,
    signal_name: str,
    x_column: str,
    title: str,
    x_axis_title: str,
) -> go.Figure:
    grouped_case_names = sorted(prepared_table["case_group"].astype(str).unique())
    figure = make_subplots(
        rows=len(grouped_case_names),
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.03,
        subplot_titles=[f"{signal_name} group {group_name}" for group_name in grouped_case_names],
    )

    for row_index, group_name in enumerate(grouped_case_names, start=1):
        group_table = prepared_table.loc[
            prepared_table["case_group"].astype(str) == group_name
        ]
        for _, case_table in group_table.groupby("case_name", sort=True):
            ordered_case_table = case_table.sort_values(by=x_column).reset_index(drop=True)
            figure.add_trace(
                _overview_trace(
                    case_table=ordered_case_table,
                    signal_name=signal_name,
                    x_column=x_column,
                ),
                row=row_index,
                col=1,
            )
        figure.update_yaxes(title_text=signal_name, row=row_index, col=1)

    figure.update_xaxes(title_text=x_axis_title, row=len(grouped_case_names), col=1)
    figure.update_layout(
        title=title,
        template=PLOT_TEMPLATE,
        width=1200,
        height=max(900, 260 * len(grouped_case_names)),
        legend_title="Case",
    )
    return figure


"""
Function: _build_dataset_overview_figures.
Builds the requested set of all-case and grouped overview plots for `cl`, `cd`,
and `pitch`, including the retained first-0.25-second zoom views.
"""


def _build_dataset_overview_figures(prepared_table: pd.DataFrame) -> list[go.Figure]:
    figures: list[go.Figure] = []
    full_range_table = _prepare_case_time_axes(prepared_table)
    zoom_table = _zoomed_table(full_range_table)

    for signal_name in ["cl", "cd", "pitch"]:
        figures.append(
            _build_all_case_signal_figure(
                prepared_table=full_range_table,
                signal_name=signal_name,
                x_column="flow_time",
                title=f"All Cases: {signal_name} vs Flow Time",
                x_axis_title="Flow Time",
            )
        )
        figures.append(
            _build_grouped_signal_figure(
                prepared_table=full_range_table,
                signal_name=signal_name,
                x_column="flow_time",
                title=f"Grouped by Case Category: {signal_name} vs Flow Time",
                x_axis_title="Flow Time",
            )
        )
        figures.append(
            _build_all_case_signal_figure(
                prepared_table=zoom_table,
                signal_name=signal_name,
                x_column="time_from_case_start",
                title=(
                    f"All Cases: {signal_name} over First "
                    f"{ZOOM_WINDOW_SECONDS:.2f} Seconds"
                ),
                x_axis_title="Retained Time From Case Start",
            )
        )
        figures.append(
            _build_grouped_signal_figure(
                prepared_table=zoom_table,
                signal_name=signal_name,
                x_column="time_from_case_start",
                title=(
                    f"Grouped by Case Category: {signal_name} over First "
                    f"{ZOOM_WINDOW_SECONDS:.2f} Seconds"
                ),
                x_axis_title="Retained Time From Case Start",
            )
        )

    return figures


"""
Section 5: Prediction-comparison figure builders.
These helpers build the time-series, residual, parity, and summary-bar figures
used to assess the latest confirmation predictions against the true data.
"""


"""
Function: _build_prediction_overlay_figure.
Creates a subplot figure comparing true and predicted trajectories for one
selected state variable across all available confirmation cases.
"""


def _build_prediction_overlay_figure(
    prediction_table: pd.DataFrame,
    state_name: str,
) -> go.Figure:
    case_names = sorted(prediction_table["case_name"].astype(str).unique())
    figure = make_subplots(
        rows=len(case_names),
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.04,
        subplot_titles=[f"{state_name}: {case_name}" for case_name in case_names],
    )

    for row_index, case_name in enumerate(case_names, start=1):
        case_table = (
            prediction_table.loc[prediction_table["case_name"].astype(str) == case_name]
            .sort_values(by="flow_time")
            .reset_index(drop=True)
        )
        figure.add_trace(
            go.Scatter(
                x=case_table["flow_time"],
                y=case_table[state_name],
                mode="lines",
                name=f"{case_name} actual",
                legendgroup=f"{case_name}_actual",
            ),
            row=row_index,
            col=1,
        )
        figure.add_trace(
            go.Scatter(
                x=case_table["flow_time"],
                y=case_table[f"{state_name}_pred"],
                mode="lines",
                name=f"{case_name} predicted",
                legendgroup=f"{case_name}_predicted",
                line={"dash": "dash"},
            ),
            row=row_index,
            col=1,
        )
        figure.update_yaxes(title_text=state_name, row=row_index, col=1)

    figure.update_xaxes(title_text="Flow Time", row=len(case_names), col=1)
    figure.update_layout(
        title=f"{state_name.upper()} Prediction vs Actual",
        template=PLOT_TEMPLATE,
        width=1200,
        height=max(650, 280 * len(case_names)),
        legend_title="Trace",
    )
    return figure


"""
Function: _build_residual_figure.
Creates a residual-vs-time figure for one selected state variable across the
available confirmation cases.
"""


def _build_residual_figure(
    prediction_table: pd.DataFrame,
    state_name: str,
) -> go.Figure:
    residual_column = f"{state_name}_residual"
    case_names = sorted(prediction_table["case_name"].astype(str).unique())
    figure = make_subplots(
        rows=len(case_names),
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.04,
        subplot_titles=[f"{state_name} residual: {case_name}" for case_name in case_names],
    )

    for row_index, case_name in enumerate(case_names, start=1):
        case_table = (
            prediction_table.loc[prediction_table["case_name"].astype(str) == case_name]
            .sort_values(by="flow_time")
            .reset_index(drop=True)
        )
        figure.add_trace(
            go.Scatter(
                x=case_table["flow_time"],
                y=case_table[residual_column],
                mode="lines",
                name=case_name,
                legendgroup=case_name,
            ),
            row=row_index,
            col=1,
        )
        figure.add_hline(y=0.0, line_color="black", line_width=1, row=row_index, col=1)
        figure.update_yaxes(title_text=residual_column, row=row_index, col=1)

    figure.update_xaxes(title_text="Flow Time", row=len(case_names), col=1)
    figure.update_layout(
        title=f"{state_name.upper()} Residuals vs Flow Time",
        template=PLOT_TEMPLATE,
        width=1200,
        height=max(650, 280 * len(case_names)),
        legend_title="Case",
    )
    return figure


"""
Function: _build_parity_figure.
Creates a parity scatter for one selected state variable, together with a
reference diagonal so over- and under-prediction can be seen quickly.
"""


def _build_parity_figure(
    prediction_table: pd.DataFrame,
    state_name: str,
) -> go.Figure:
    x_values = prediction_table[state_name]
    y_values = prediction_table[f"{state_name}_pred"]
    lower_limit = float(min(x_values.min(), y_values.min()))
    upper_limit = float(max(x_values.max(), y_values.max()))

    figure = go.Figure()
    for case_name, case_table in prediction_table.groupby("case_name", sort=True):
        figure.add_trace(
            go.Scatter(
                x=case_table[state_name],
                y=case_table[f"{state_name}_pred"],
                mode="markers",
                name=str(case_name),
                legendgroup=str(case_name),
                opacity=0.7,
            )
        )

    figure.add_trace(
        go.Scatter(
            x=[lower_limit, upper_limit],
            y=[lower_limit, upper_limit],
            mode="lines",
            name="y = x",
            line={"color": "black", "dash": "dash"},
        )
    )
    figure.update_layout(
        title=f"{state_name.upper()} Parity Plot",
        template=PLOT_TEMPLATE,
        width=850,
        height=750,
        legend_title="Case",
    )
    figure.update_xaxes(title_text=f"True {state_name}", scaleanchor="y", scaleratio=1)
    figure.update_yaxes(title_text=f"Predicted {state_name}")
    return figure


"""
Function: _build_error_bar_figure.
Creates a bar chart for the requested pair of per-case error metrics using the
latest run summary written by the run stage.
"""


def _build_error_bar_figure(
    run_summary_table: pd.DataFrame,
    metric_pair: tuple[str, str],
    title: str,
) -> go.Figure:
    ordered_summary_table = run_summary_table.sort_values(by="case_name").reset_index(drop=True)
    figure = go.Figure()
    for metric_name in metric_pair:
        figure.add_trace(
            go.Bar(
                x=ordered_summary_table["case_name"],
                y=ordered_summary_table[metric_name],
                name=metric_name,
            )
        )

    figure.update_layout(
        title=title,
        template=PLOT_TEMPLATE,
        width=1000,
        height=650,
        barmode="group",
        legend_title="Metric",
    )
    figure.update_xaxes(title_text="Confirmation Case")
    figure.update_yaxes(title_text="Error")
    return figure


"""
Function: _build_prediction_comparison_figures.
Builds the first analysis pack for prediction quality using the latest run
outputs already produced by the pipeline.
"""


def _build_prediction_comparison_figures(
    prediction_table: pd.DataFrame,
    run_summary_table: pd.DataFrame,
) -> list[go.Figure]:
    prepared_prediction_table = _prepare_case_time_axes(prediction_table)
    return [
        _build_prediction_overlay_figure(prepared_prediction_table, "cl"),
        _build_prediction_overlay_figure(prepared_prediction_table, "cd"),
        _build_residual_figure(prepared_prediction_table, "cl"),
        _build_residual_figure(prepared_prediction_table, "cd"),
        _build_parity_figure(prepared_prediction_table, "cl"),
        _build_parity_figure(prepared_prediction_table, "cd"),
        _build_error_bar_figure(
            run_summary_table=run_summary_table,
            metric_pair=("rmse_cl", "rmse_cd"),
            title="Per-Case RMSE",
        ),
        _build_error_bar_figure(
            run_summary_table=run_summary_table,
            metric_pair=("mae_cl", "mae_cd"),
            title="Per-Case MAE",
        ),
    ]


"""
Section 6: Public analysis entry point.
This final section coordinates loading the existing outputs, building the full
overview and comparison figure set, and displaying those figures for review.
The tuned-vs-untuned comparison plots are intentionally deferred to a later
increment once tuned outputs have their own stable workflow.
"""


"""
Function: run_analysis_stage.
Runs the first V2 analysis stage using the prepared outputs and latest run
outputs already written by the earlier stages.
"""


def run_analysis_stage() -> AnalysisStageOutput:
    prepared_table, prediction_table, run_summary_table = _load_analysis_inputs()

    figures = _build_dataset_overview_figures(prepared_table)
    figures.extend(
        _build_prediction_comparison_figures(
            prediction_table=prediction_table,
            run_summary_table=run_summary_table,
        )
    )

    for figure_index, figure in enumerate(figures, start=1):
        _show_figure(
            figure=figure,
            figure_index=figure_index,
            total_figures=len(figures),
        )

    print(
        "[analyse] tuned-vs-untuned comparison plots are intentionally deferred "
        "to a later increment",
        flush=True,
    )

    return AnalysisStageOutput(
        displayed_figure_count=len(figures),
        prepared_case_count=int(prepared_table["case_name"].nunique()),
        confirmation_case_count=int(prediction_table["case_name"].nunique()),
    )


if __name__ == "__main__":
    run_analysis_stage()
