import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

### %E AVG CALC ###
"""
calculates the average percentage error between true and predicted values;
this will be used in the analysis part to see if some modules are more accurate for certain variables
    compared to others
"""

def calculate_average_percentage_error(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    non_zero_mask = y_true != 0
    ape = np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask]) * 100
    return np.mean(ape) if ape.size > 0 else 0



### FEATURE IMPORTANCE ###
"""
define functions for getting feature importance for each model.
this will then be used in analyse.py to get the feature importance for each model
"""

def get_random_forest_feature_importance(model, feature_names):
    feature_importances = model.feature_importances_
    importance_dict = dict(zip(feature_names, feature_importances))
    return dict(sorted(importance_dict.items(), key=lambda item: item[1], reverse=True))

def get_decision_tree_feature_importance(model, feature_names):
    feature_importances = model.feature_importances_
    importance_dict = dict(zip(feature_names, feature_importances))
    return dict(sorted(importance_dict.items(), key=lambda item: item[1], reverse=True))

def get_linear_regression_coefficients(model, feature_names):
    coefficients = model.coef_
    feature_importance = {}
    for i, feature in enumerate(feature_names):
        avg_abs_coef = np.mean(np.abs(coefficients[:, i]))
        feature_importance[feature] = avg_abs_coef
    return dict(sorted(feature_importance.items(), key=lambda item: item[1], reverse=True))

def get_custom_linear_regression_coefficients(model, feature_names):
    """Extracts coefficients from your custom Linear Regression model."""
    if model.coef_ is not None and len(model.coef_) == len(feature_names) + 1:
        # The first element of coef_ is the intercept
        coefficients = model.coef_[1:]
        return dict(zip(feature_names, coefficients))
    else:
        return {}

def get_ridge_regression_coefficients(model, feature_names):
    coefficients = model.coef_
    feature_importance = {}
    for i, feature in enumerate(feature_names):
        avg_abs_coef = np.mean(np.abs(coefficients[:, i]))
        feature_importance[feature] = avg_abs_coef
    return dict(sorted(feature_importance.items(), key=lambda item: item[1], reverse=True))

def get_lasso_regression_coefficients(model, feature_names):
    coefficients = model.coef_
    feature_importance = {}
    for i, feature in enumerate(feature_names):
        avg_abs_coef = np.mean(np.abs(coefficients[:, i]))
        feature_importance[feature] = avg_abs_coef
    return dict(sorted(feature_importance.items(), key=lambda item: item[1], reverse=True))

def get_elastic_net_coefficients(model, feature_names):
    coefficients = model.coef_
    feature_importance = {}
    for i, feature in enumerate(feature_names):
        avg_abs_coef = np.mean(np.abs(coefficients[:, i]))
        feature_importance[feature] = avg_abs_coef
    return dict(sorted(feature_importance.items(), key=lambda item: item[1], reverse=True))


def get_polynomial_regression_feature_importance(model, original_feature_names, degree):
    """Estimates feature importance for Polynomial Regression."""
    if not hasattr(model, 'coef_'):
        return {}

    coefs = model.coef_

    # Handle multi-output by averaging absolute coefficients
    if coefs.ndim > 1 and coefs.shape[0] > 1:
        coefs = np.mean(np.abs(coefs), axis=0)
    else:
        coefs = np.abs(coefs.ravel()) # Ensure 1D abs values


    # Recreate a temporary PolynomialFeatures transformer to get the polynomial feature names
    try:
        temp_poly = PolynomialFeatures(degree=degree, include_bias=False)
        # Fit on dummy data just to generate the feature names structure
        dummy_X = np.zeros((1, len(original_feature_names)))
        temp_poly.fit(dummy_X)
        # Get the names of the polynomial features generated by the transformer
        poly_feature_names = temp_poly.get_feature_names_out(original_feature_names)

    except Exception:
        # Return empty on error
        return {}

    # Ensure the number of coefficients matches the number of polynomial features
    if len(coefs) != len(poly_feature_names):
        return {}

    poly_coef_dict = dict(zip(poly_feature_names, coefs))
    original_feature_importance = {name: 0 for name in original_feature_names}

    for poly_name, coef in poly_coef_dict.items():
        # Identify which original features are in this polynomial term name
        # Split by spaces to get individual feature terms (e.g., 'feature1', 'feature2^2')
        terms_in_poly_name = poly_name.split()
        features_in_term = set()
        for term in terms_in_poly_name:
            # Split by '^' and take the base feature name
            base_feature_name = term.split('^')[0]
            # If this base name is one of our original features, add it to the set
            if base_feature_name in original_feature_names:
                 features_in_term.add(base_feature_name)

        # Add the absolute coefficient to the total for each original feature in this term
        for original_name in features_in_term:
             original_feature_importance[original_name] += coef


    return dict(sorted(original_feature_importance.items(), key=lambda item: item[1], reverse=True))



"""
SVR and KNN dont have feature importance metrics so we dont add them
"""